plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

repositories {
	maven {
		name = 'NeoForged'
		url = 'https://maven.neoforged.net/releases'
	}
	maven {
		name = 'MinecraftForge'
		url = 'https://maven.minecraftforge.net/'
	}
	mavenCentral()
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"beatlamp" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets {
	neoforge {
		java {
			srcDirs = ['neoforge/src/main/java']
		}
		resources {
			srcDirs = ['neoforge/src/main/resources']
		}
		compileClasspath += sourceSets.main.output + sourceSets.client.output + sourceSets.main.compileClasspath + sourceSets.client.compileClasspath
		runtimeClasspath += sourceSets.main.output + sourceSets.client.output + sourceSets.main.runtimeClasspath + sourceSets.client.runtimeClasspath
	}
	forge {
		java {
			srcDirs = ['forge/src/main/java']
		}
		resources {
			srcDirs = ['forge/src/main/resources']
		}
		compileClasspath += sourceSets.main.output + sourceSets.client.output + sourceSets.main.compileClasspath + sourceSets.client.compileClasspath
		runtimeClasspath += sourceSets.main.output + sourceSets.client.output + sourceSets.main.runtimeClasspath + sourceSets.client.runtimeClasspath
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// NeoForge dependencies for multi-loader compilation
	neoforgeImplementation "net.neoforged:neoforge:21.1.80:universal"
	neoforgeImplementation "net.neoforged.fancymodloader:loader:4.0.31"
	neoforgeImplementation "net.neoforged:bus:8.0.2"
	neoforgeImplementation sourceSets.main.output
	neoforgeImplementation sourceSets.client.output

	// Forge dependencies for multi-loader compilation
	forgeImplementation "net.minecraftforge:forge:1.21.1-52.0.57:universal"
	forgeImplementation "net.minecraftforge:javafmllanguage:1.21.1-52.0.57"
	forgeImplementation "net.minecraftforge:fmlcore:1.21.1-52.0.57"
	forgeImplementation "net.minecraftforge:fmlloader:1.21.1-52.0.57"
	forgeImplementation "net.minecraftforge:forgespi:7.1.5"
	forgeImplementation "net.minecraftforge:eventbus:6.2.27"
	forgeImplementation sourceSets.main.output
	forgeImplementation sourceSets.client.output
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.compilerArgs << "-Xlint:deprecation"
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName
	archiveClassifier = 'fabric'

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

remapJar {
	archiveFileName = "beatlamp-fabric-${project.minecraft_version}-${project.version}.jar"
}

remapSourcesJar {
	archiveFileName = "beatlamp-sources-${project.minecraft_version}-${project.version}.jar"
}

task neoforgeJar(type: Jar, dependsOn: [classes, clientClasses, neoforgeClasses]) {
	def projectName = project.name
	archiveFileName = "beatlamp-neoforge-${project.minecraft_version}-${project.version}.jar"
	from sourceSets.main.output
	from sourceSets.client.output
	from sourceSets.neoforge.output
	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
	exclude 'fabric.mod.json'
	exclude 'beatlamp.client.mixins.json'
	exclude 'com/beatlamp/fabric/**'
}

task forgeJar(type: Jar, dependsOn: [classes, clientClasses, forgeClasses]) {
	def projectName = project.name
	archiveFileName = "beatlamp-forge-${project.minecraft_version}-${project.version}.jar"
	from sourceSets.main.output
	from sourceSets.client.output
	from sourceSets.forge.output
	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
	exclude 'fabric.mod.json'
	exclude 'beatlamp.client.mixins.json'
	exclude 'com/beatlamp/fabric/**'
}

assemble.dependsOn neoforgeJar, forgeJar

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
