modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/HyIsNoob/modMinecraft/issues"

[[mods]]
modId="beatlamp"
version="1.1.0"
displayName="Beat Lamp"
authors="HyIsNoob"
description='''
Audio-reactive concert lighting, stage effects, RGB Laser Projector, Stage Fog Generator, and redstone signals synced to jukebox music in real time.
'''
logoFile="icon.png"

[[dependencies.beatlamp]]
modId="neoforge"
type="required"
versionRange="[21.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.beatlamp]]
modId="minecraft"
type="required"
versionRange="[1.21.4,1.22)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="beatlamp.mixins.json"

[[mixins]]
config="beatlamp.client.mixins.json"

