plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

repositories {
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:1.20.1"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:0.16.10"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.2+1.20.1"
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

processResources {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	def version = project.version
	inputs.property "version", version

	from("${project.rootDir}/src/main/resources") {
		exclude 'fabric.mod.json'
		exclude 'beatlamp.mixins.json'
		exclude 'beatlamp.client.mixins.json'
		exclude 'pack.mcmeta'
	}
	from("${project.rootDir}/src/client/resources") {
		exclude 'beatlamp.client.mixins.json'
	}
	from("src/main/resources")

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

remapJar {
	archiveFileName = "beatlamp-fabric-1.20.1-${project.version}.jar"
}
